# Source: docs/specs/06-spec-self-development/06-spec-self-development.md
# Pattern: CLI/Process + State
# Recommended test type: Integration

Feature: Self-Modification -- Agent-Generated PRs

  Scenario: Bug-fix workflow creates branch and opens PR
    Given a workflow file "workflows/bug-fix.yaml" exists with pr:create tool binding
    And the ANTHROPIC_API_KEY environment variable is set
    And the target directory is a git repository
    When the user runs "agentry run workflows/bug-fix.yaml --input issue-description='Fix typo in README' --target . --output-format json"
    Then the command exits with code 0
    And stdout contains valid JSON with a "branch" field containing a branch name
    And the JSON output contains a "pr_url" field with a URL or local branch reference

  Scenario: Agent-created PR is labeled with agent-proposed tag
    Given the bug-fix workflow has been run and a PR was created
    When the PR is inspected on the target repository
    Then the PR has the label "agent-proposed"
    And the PR targets the default base branch "main"

  Scenario: Agent-created PR is not auto-merged
    Given the bug-fix workflow has been run and a PR was created
    When the PR is inspected on the target repository
    Then the PR status is "open" and not "merged"
    And no auto-merge configuration is enabled on the PR

  Scenario: Local binder pr:create creates branch and commits changes
    Given the local binder is configured with pr:create tool binding
    And a temporary git repository exists with an initial commit
    When the bug-fix workflow runs against the temporary repository
    Then a new branch is created in the temporary repository
    And the branch contains at least one commit with proposed changes
    And the original branch is not modified

  Scenario: GitHub Actions binder pr:create opens a pull request
    Given the github-actions binder is configured with pr:create tool binding
    And the GITHUB_TOKEN environment variable is set
    And the target is a GitHub-hosted repository
    When the bug-fix workflow runs with the github-actions binder
    Then a pull request is opened on the GitHub repository
    And the PR has a descriptive title and body generated by the agent

  Scenario: pr:create tool binding refuses to force-push or target protected branches
    Given the pr:create tool binding is configured
    And a git repository with a protected branch "main" exists
    When the agent attempts to force-push to "main" via the pr:create tool
    Then the operation is rejected with an error
    And no force-push is performed
    And the protected branch remains unmodified
