"""Data models for LLM client requests and responses.

These types are shared between the LLMClient protocol and all provider
implementations. They are intentionally provider-agnostic.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class LLMMessage:
    """A single message in a conversation turn.

    Attributes:
        role: The message role, either ``"user"`` or ``"assistant"``.
        content: The text content of the message.
    """

    role: str
    content: str


@dataclass
class LLMToolDefinition:
    """A tool definition passed to the LLM for Claude tool-use.

    Attributes:
        name: Tool identifier (e.g. ``"repository:read"``).
        description: Human-readable description of what the tool does.
        input_schema: JSON Schema dict describing the tool's input parameters.
    """

    name: str
    description: str
    input_schema: dict[str, Any]


@dataclass
class LLMConfig:
    """Configuration that controls how the LLM call is made.

    Attributes:
        model: Model identifier string (e.g. ``"claude-sonnet-4-5"``).
        temperature: Sampling temperature in [0, 1]. Defaults to 1.0.
        max_tokens: Maximum number of tokens to generate.
        timeout: Optional per-call timeout in seconds. ``None`` means no limit.
    """

    model: str
    max_tokens: int
    temperature: float = 1.0
    timeout: float | None = None


@dataclass
class TokenUsage:
    """Token usage statistics from a single LLM call.

    Attributes:
        input_tokens: Number of tokens in the prompt (including system prompt).
        output_tokens: Number of tokens generated by the model.
    """

    input_tokens: int
    output_tokens: int

    @property
    def total_tokens(self) -> int:
        """Total tokens consumed by the call."""
        return self.input_tokens + self.output_tokens


@dataclass
class LLMResponse:
    """The result of a single LLM call.

    Attributes:
        content: The text content of the model's response. May be an empty
            string if the model's last action was a tool invocation with no
            trailing text.
        tool_calls: Tool invocations the model made, each as a dict with keys
            ``name`` and ``input``. Empty list if the model produced no tool
            calls.
        usage: Token consumption for this call.
        model: The model identifier actually used (echoed from the response).
        stop_reason: Why the model stopped (``"end_turn"``, ``"tool_use"``,
            ``"max_tokens"``, etc.).
    """

    content: str
    tool_calls: list[dict[str, Any]] = field(default_factory=list)
    usage: TokenUsage = field(default_factory=lambda: TokenUsage(0, 0))
    model: str = ""
    stop_reason: str = ""
